version: '3.4'

services:
  db:
    build:
      context: ./db/
      args:
        DB_USER: "${DB_USER}"
        DB_PASSWORD: "${DB_PASSWORD}"
        DB_NAME: "${DB_NAME}"
    hostname: db
    env_file:
      - ./db.env
    volumes:
      - inventory_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
    inventory_data:
