# Generated by Django 4.0.1 on 2022-01-31 22:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_item_unit_size_alter_item_common_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='vendor/donator name')),
                ('active', models.BooleanField(default=True, verbose_name='usable source')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='item name')),
                ('common_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_items', to='inventory.commonitem')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='incoming.source')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incoming.source')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_items', to='incoming.item')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='incoming.incomingitems')),
            ],
        ),
    ]
