# Generated by Django 4.0.1 on 2022-01-31 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incoming', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='common_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_items', to='inventory.commonitem'),
        ),
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='incoming.source'),
        ),
        migrations.AddField(
            model_name='incomingitemgroup',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incoming.source'),
        ),
        migrations.AddField(
            model_name='incomingitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_items', to='incoming.item'),
        ),
        migrations.AddField(
            model_name='incomingitem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='incoming.incomingitemgroup'),
        ),
    ]
