# Generated by Django 4.0.1 on 2022-02-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingitemgroup',
            name='descriptor',
            field=models.CharField(default='', max_length=1024, verbose_name='some uniquish descriptor'),
            preserve_default=False,
        ),
    ]
