# Generated by Django 4.0.1 on 2022-02-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0003_incomingitemgroup_descriptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='incomingitem',
            name='unit_size',
            field=models.CharField(default='count', max_length=1024),
        ),
    ]
