# Generated by Django 4.0.1 on 2022-02-01 19:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0004_incomingitem_quantity_incomingitem_unit_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomingitemgroup',
            name='action_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incomingitemgroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SourceIncomingDetailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('position', models.PositiveSmallIntegerField(null=True, verbose_name='Position')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_templates', to='incoming.source')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='IncomingItemGroupDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('content', models.CharField(blank=True, default='', max_length=1024)),
                ('position', models.PositiveSmallIntegerField(null=True, verbose_name='Position')),
                ('incoming_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='incoming.incomingitemgroup')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
