# Generated by Django 4.0.1 on 2022-02-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0005_incomingitem_created_incomingitemgroup_action_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceincomingdetailtemplate',
            name='description',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
