# Generated by Django 4.0.1 on 2022-02-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0006_alter_sourceincomingdetailtemplate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='do_not_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
