# Generated by Django 4.0.1 on 2022-02-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0007_item_do_not_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingitemgroup',
            name='descriptor',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='some uniquish descriptor'),
        ),
    ]
