# Generated by Django 4.0.1 on 2022-02-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0008_alter_incomingitemgroup_descriptor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomingitem',
            old_name='quantity',
            new_name='delivered_quantity',
        ),
        migrations.RemoveField(
            model_name='incomingitem',
            name='unit_size',
        ),
        migrations.AddField(
            model_name='incomingitem',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Anything noteworthy about this item'),
        ),
        migrations.AddField(
            model_name='incomingitem',
            name='extended_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='incomingitem',
            name='ordered_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='incomingitem',
            name='total_weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='incomingitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='incomingitem',
            name='unit_tax',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='incomingitemgroup',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Anything noteworthy about this order'),
        ),
        migrations.AddField(
            model_name='item',
            name='pack_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_size',
            field=models.CharField(default='count', max_length=1024),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Probably cryptic item name'),
        ),
    ]
