# Generated by Django 4.0.1 on 2022-02-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0009_rename_quantity_incomingitem_delivered_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discontinued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='identifier',
            field=models.CharField(blank=True, default='', help_text='code, upc, etc.', max_length=1024),
        ),
    ]
