# Generated by Django 4.0.1 on 2022-02-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0010_item_discontinued_item_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='better_name',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Less cryptic item name'),
        ),
    ]
