# Generated by Django 4.0.1 on 2022-02-04 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_category_location_commonitem_category_and_more'),
        ('incoming', '0011_item_better_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='common_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_items', to='inventory.commonitem'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('source', 'identifier', 'name', 'pack_quantity', 'unit_size'), name='unique_source_id_name_packqty_size'),
        ),
    ]
