# Generated by Django 4.0.1 on 2022-02-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0012_alter_item_common_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomingitem',
            old_name='unit_price',
            new_name='pack_price',
        ),
        migrations.RenameField(
            model_name='incomingitem',
            old_name='unit_tax',
            new_name='pack_tax',
        ),
        migrations.AddField(
            model_name='item',
            name='individual_serving',
            field=models.BooleanField(default=False, help_text='Is a preportioned single-serving disposable package'),
        ),
    ]
