# Generated by Django 4.0.2 on 2022-02-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0013_rename_unit_price_incomingitem_pack_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingitem',
            name='line_item_position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
    ]
