# Generated by Django 4.0.2 on 2022-02-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0014_incomingitem_line_item_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingitemgroup',
            name='converted_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
