# Generated by Django 4.0.1 on 2022-02-10 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0015_incomingitemgroup_converted_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingitemgroup',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_groups', to='incoming.source'),
        ),
    ]
