# Generated by Django 4.0.1 on 2022-02-13 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0017_incomingitemgroup_total_packs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingitem',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='items', to='incoming.incomingitemgroup'),
        ),
    ]
