# Generated by Django 4.0.1 on 2022-02-21 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0018_alter_incomingitem_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomingitem',
            options={'ordering': ('parent', 'line_item_position')},
        ),
    ]
