# Generated by Django 4.0.1 on 2022-02-24 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_commonitem_options_alter_item_options'),
        ('incoming', '0019_alter_incomingitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='common_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_items', related_query_name='incoming_items', to='inventory.commonitem'),
        ),
    ]
