# Generated by Django 4.0.1 on 2022-02-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0020_alter_item_common_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Anything noteworthy about this item'),
        ),
    ]
