# Generated by Django 4.0.1 on 2022-02-28 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_department'),
        ('incoming', '0021_item_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingitemgroup',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_groups', to='inventory.department'),
        ),
        migrations.AddField(
            model_name='incomingitemgroup',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='possibly unique text - some sources repeat this for backordered items'),
        ),
        migrations.AddField(
            model_name='incomingitemgroup',
            name='po_text',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='optional text likely on the invoice'),
        ),
    ]
