# Generated by Django 4.0.1 on 2022-02-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0022_incomingitemgroup_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingitemgroup',
            name='comment',
            field=models.CharField(blank=True, default='', help_text='Anything noteworthy about this order', max_length=1024),
        ),
        migrations.AlterField(
            model_name='incomingitemgroup',
            name='descriptor',
            field=models.CharField(blank=True, default='', help_text='some uniquish descriptor', max_length=1024),
        ),
        migrations.AlterField(
            model_name='incomingitemgroup',
            name='order_number',
            field=models.CharField(blank=True, default='', help_text='possibly unique text - some sources repeat this for backordered items', max_length=1024),
        ),
        migrations.AlterField(
            model_name='incomingitemgroup',
            name='po_text',
            field=models.CharField(blank=True, default='', help_text='optional text likely on the invoice', max_length=1024),
        ),
    ]
