---
- name: Include distribution specific variables for inventory app
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts.os_family }}-{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
    - "{{ ansible_facts.os_family }}.yml"
    - "{{ ansible_facts.os_distribution }}.yml"
    - defaults/main.yml

- name: Initial setup of inventory app
  block:
    - include_tasks: "setup-os-{{ ansible_facts.os_family }}.yml"
    - include_tasks: deploy-code.yml
    - include_tasks: "setup-python-env.yml"
    - include_tasks: service.yml
      when: ansible_facts.distribution != 'MacOSX'
  when: process_items is not defined or not process_items

- name: Loading data to inventory app
  block:
    - include_tasks: process_data.yml
  when: process_items is defined and process_items
