---
- name: add www-data group to {{ default_user }} groups
  user: >
    name={{ default_user }} 
    append=true 
    groups=www-data 
    state=present
  become: yes

- name: create the service to start the inventory app http server
  template:
    src: "service.j2"
    dest: "/lib/systemd/system/{{ service_name }}.service"
    mode: 0644
  become: yes
  notify: restart inventory app http service

- name: install uwsgi for Inventory App
  pip: name=uwsgi virtualenv={{ venv_folder }}
  register: result
  retries: 3 # total attempts to make.  Not 1 + 3.
  delay: 3 # seconds
  changed_when: '"Successfully installed" in result["stdout"]'
  failed_when: result['failed']

# Permissions for /srv/sos/log/www will be www-data:ampops
- name: create log/www dir under application root
  file: >
    path={{ srv_folder }}/log/www 
    state=directory 
    owner={{ default_nginx_apps_uid }} 
    group=www-data 
    mode=0775
  become: yes

# Permissions for /srv/sos/log will be ampops:www-data
- name: create application log dir
  file: >
    path={{ srv_folder }}/log
    state=directory
    owner={{ default_user }}
    group={{ default_group }}
    mode=0775
  become: yes

- name: disable the default nginx app config
  file: >
    path={{ inventory_app_nginx_root_dir }}/sites-enabled/default
    state=absent
  notify:
    - restart nginx
  become: yes

- name: create uwsgi socket root dir
  file: >
    path={{ inventory_app_uwsgi_socket_file_root }}
    state=directory
    group=www-data
    owner={{ default_nginx_apps_uid }}
    mode=0775
  become: yes

- name: make sure nginx config directories exists
  file: >
    path="{{ inventory_app_nginx_root_dir }}/{{ item }}"
    state=directory
    owner=root
    group="root"
    mode=0755
  become: yes
  with_items: ['sites-available', 'sites-enabled']

- name: set inventory app http service to start automagically
  service:
    name: "{{ service_name }}"
    enabled: yes
  become: yes
  notify: restart inventory app http service

- name: Configure inventory app http rsyslog entries
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR {{ service_name }}"
    block: |
      /var/log/{{ service_log }}
      {
      	rotate 4
      	weekly
      	missingok
      	notifempty
      	compress
      	delaycompress
      	sharedscripts
      	postrotate
      		/usr/lib/rsyslog/rsyslog-rotate
      	endscript
      }
    create: yes
    owner: root
    group: root
    insertafter: EOF
    mode: "0644"
    path: "/etc/logrotate.d/rsyslog"
  become: yes

- name: Configure logging filter for inventory app http server
  blockinfile:
    block: |
      if $programname == '{{ service_syslog_id }}' then /var/log/{{ service_log }}
      & stop
    create: yes
    owner: root
    group: root
    insertafter: EOF
    mode: "0644"
    path: "/etc/rsyslog.d/{{ service_syslog_id }}.conf"
  become: yes
  notify: restart rsyslog

- name: Add inventory app http service to service_status script
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR {{ item.service }}"
    block: |
      echo "------- {{ item.service }} ------- {{ item.service }} ------- {{ item.service }} -------"
      systemctl status --no-pager {{ item.service }}
      echo "------------------------------------------------------------------------------"
    dest: "{{ default_home_dir }}/service_status.sh"
    state: "{{ item.state }}"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: 0755
    insertafter: EOF
  with_items:
    - {"service": "{{ service_name }}", "state": "present"}

- name: Add inventory app service to short_service_status script
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR {{ item.service }}"
    block: |
      echo "$(systemctl is-active --no-pager {{item.service}}) - {{item.service}}"
    dest: "{{ default_home_dir }}/short_service_status.sh"
    state: "{{ item.state }}"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: 0755
    insertafter: EOF
  loop:
    - {"service": "{{ service_name }}", "state": "present"}

- name: Create/Update Inventory App nginx configuration file
  template: >
    src=nginx-inventory-app.conf.j2 
    dest={{ inventory_app_nginx_conf_file_path }}
  become: yes
  notify:
    - restart nginx

- name: enable desired nginx site configs
  file: >
    dest="{{ inventory_app_nginx_root_dir }}/sites-enabled/{{ item.filename }}"
    src="{{ inventory_app_nginx_root_dir }}/sites-available/{{ item.filename }}" 
    state=link
    owner=root
    group="{{ default_group }}"
  with_items: "{{ inventory_app_nginx_conf_files }}"
  become: yes
  notify:
    - restart nginx
