---
- name: Install required system packages for connecting to Postgresql
  apt:
    name: libpq5
    state: present
  become: yes

- name: add www-data group to {{ default_user }} groups
  user: >
    name={{ default_user }} 
    append=true 
    groups=www-data 
    state=present
  become: yes
