from . import export


def find_exports(folder="."):
    """
    Searches path for files matching pattern "pg_dump_YYYY-MM-DD_HHMMSS_{table_name}.sql".  Returns list of files with
    the most recent datetime slug.  Expects all files in the same export to have the same slug.
    """
    return []


def sort_files_based_on_models(files_to_sort, models_in_order):
    """
    Uses models_in_order to sort the files.  Files should be named with the pattern
    "pg_dump_YYYY-MM-DD_HHMMSS_{table_name}.sql"
    """
    return []


def modify_sql_scripts_insert_into_upsert(files_to_import):
    """
    The scripts are generated with "ON CONFLICT DO NOTHING;".  This changes the "DO NOTHING" into an update.
    """
    pass


def generate_import_commands(files_to_import):
    """
    Generates a list of commands to import the specified files.
    """
    return []


def run():
    """
    Imports each model's data in the order that respects dependencies.  To be used with sql files generated by the
    export runscript.
    """
    model_list = export.get_models_to_sort()
    models_in_order = export.sort_models(model_list)
    print(models_in_order)
    files_to_import = find_exports()
    sorted_files_to_import = sort_files_based_on_models(files_to_import, models_in_order)
    modify_sql_scripts_insert_into_upsert(sorted_files_to_import)
    import_commands = generate_import_commands(sorted_files_to_import)
    # print(import_commands[-1])
    # export.execute_commands(import_commands)
