# Generated by Django 4.0.6 on 2022-10-15 23:02

from django.db import migrations, models
import django.db.models.deletion
import scrap.models.fields.char_field
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0014_alter_sourceitem_remaining_count_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('cryptic_name', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='Source-specific name of item as it appears on invoices', max_length=1024)),
                ('verbose_name', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='More human-readable name of the item', max_length=1024)),
                ('common_name', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='Common brand-less name of item', max_length=1024)),
                ('item_code', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='String of text that should uniquely identify the item', max_length=1024)),
                ('measuring_unit', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='Usually some volume unit like cups or gallons', max_length=1024)),
                ('measuring_count', models.DecimalField(decimal_places=4, help_text='How many of measuring_unit will be used', max_digits=9)),
                ('converted_unit', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='Usually grams', max_length=1024)),
                ('converted_amount', models.DecimalField(decimal_places=4, help_text='How much of converted unit did the measuring produce', max_digits=9)),
                ('avg_converted_per_measuring', models.DecimalField(decimal_places=4, help_text='Value to use when manually converting', max_digits=9)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.sourceitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
