# Generated by Django 4.0.6 on 2022-10-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_measure_measure_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measure',
            options={'ordering': ('-measure_date', '-modified')},
        ),
    ]
