# Generated by Django 4.0.6 on 2023-08-24 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_searchcriteria_options'),
        ('conversion', '0003_alter_measure_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='measures', related_query_name='measures', to='inventory.sourceitem'),
        ),
    ]
