# Generated by Django 4.0.1 on 2022-03-06 05:37

from django.db import migrations
import scrap.models.fields.char_field


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_squashed_0005_alter_rawincomingitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawincomingitem',
            name='scanned_image_filename',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', help_text='Filename of the scanned file.  Might have multiple per order.', max_length=1024),
        ),
    ]
