# Generated by Django 4.0.1 on 2022-03-07 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rawincomingitem_scanned_image_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawstate',
            name='next_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_state', to='inventory.rawstate'),
        ),
    ]
