# Generated by Django 4.0.1 on 2022-03-21 04:18

from django.db import migrations, models
import django.db.models.deletion
import inventory.models.raw_state
import scrap.models.fields.decimal_field


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_rawincomingitem_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawincomingitem',
            name='pack_quantity',
            field=scrap.models.fields.decimal_field.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rawincomingitem',
            name='state',
            field=models.ForeignKey(default=inventory.models.raw_state.RawStateManager.initial_state, on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', related_query_name='raw_items', to='inventory.rawstate'),
        ),
        migrations.AlterField(
            model_name='rawitem',
            name='pack_quantity',
            field=scrap.models.fields.decimal_field.DecimalField(decimal_places=4, default=1, max_digits=10),
        ),
    ]
