# Generated by Django 4.0.1 on 2022-03-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rawstate_next_error_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawincomingitem',
            name='failure_reasons',
            field=models.TextField(blank=True, null=True),
        ),
    ]
