# Generated by Django 4.0.1 on 2022-03-24 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import inventory.models.raw_state
import scrap.models.fields.char_field
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_rawincomingitem_rawitem_obj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminstock',
            name='raw_incoming_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='in_stock', related_query_name='in_stock', to='inventory.rawincomingitem'),
        ),
        migrations.AlterField(
            model_name='rawincomingitem',
            name='state',
            field=models.ForeignKey(default=inventory.models.raw_state.RawStateManager.initial_state, on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', related_query_name='raw_items', to='inventory.rawstate'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', scrap.models.fields.char_field.CharField(blank=True, default='', max_length=1024)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.source')),
            ],
            options={
                'ordering': ('source__name', 'name'),
            },
        ),
        migrations.AddField(
            model_name='rawitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', related_query_name='raw_items', to='inventory.item'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('source'), django.db.models.expressions.F('name'), name='item-source-name'),
        ),
    ]
