# Generated by Django 4.0.1 on 2022-03-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rawincomingitem_failure_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawstate',
            name='failed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
