# Generated by Django 4.0.1 on 2022-03-14 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rawincomingitem_customer_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawincomingitem',
            options={'ordering': ('delivery_date', 'source', 'order_number', 'line_item_position')},
        ),
    ]
