# Generated by Django 4.0.1 on 2022-03-15 17:54

from django.db import migrations, models
import django.db.models.deletion
import scrap.fields.char_field
import scrap.fields.decimal_field
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_rawincomingitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonItemName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', scrap.fields.char_field.CharField(blank=True, default='', max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', scrap.fields.char_field.CharField(blank=True, default='', help_text='vendor/donator name', max_length=1024)),
                ('active', models.BooleanField(default=True, help_text='is a usable source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('category', scrap.fields.char_field.CharField(blank=True, default='', help_text='meat, dairy, produce, etc.', max_length=1024)),
                ('name', scrap.fields.char_field.CharField(blank=True, default='', max_length=1024)),
                ('better_name', scrap.fields.char_field.CharField(blank=True, default='', help_text='Less cryptic item name', max_length=1024)),
                ('item_code', scrap.fields.char_field.CharField(blank=True, default='', max_length=1024)),
                ('extra_code', scrap.fields.char_field.CharField(blank=True, default='', max_length=1024)),
                ('unit_size', scrap.fields.char_field.CharField(blank=True, default='', max_length=1024)),
                ('pack_quantity', scrap.fields.decimal_field.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('item_comment', scrap.fields.char_field.CharField(blank=True, default='', help_text='Anything noteworthy about this item', max_length=1024)),
                ('common_item_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.commonitemname')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', related_query_name='raw_items', to='inventory.source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='commonitemname',
            name='raw_items',
            field=models.ManyToManyField(related_name='common_item_names', related_query_name='common_item_names', to='inventory.RawItem'),
        ),
    ]
