# Generated by Django 4.0.1 on 2022-03-27 22:07

from django.db import migrations, models
import django.db.models.deletion
import inventory.models.raw_state
import scrap.models.fields.char_field


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_usagegroup_alter_rawincomingitem_state_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='comment',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', help_text='Anything special about this specific item', max_length=1024),
        ),
        migrations.AddField(
            model_name='usagegroup',
            name='comment',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', help_text='Anything special about this usage as a whole', max_length=1024),
        ),
        migrations.AlterField(
            model_name='rawincomingitem',
            name='state',
            field=models.ForeignKey(default=inventory.models.raw_state.RawStateManager.initial_state, on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', related_query_name='raw_items', to='inventory.rawstate'),
        ),
    ]
