# Generated by Django 4.0.1 on 2022-03-15 18:59

from django.db import migrations
import scrap.fields.char_field


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_commonitemname_source_rawitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=scrap.fields.char_field.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=scrap.fields.char_field.CharField(blank=True, default='', max_length=1024),
        ),
    ]
