# Generated by Django 4.0.1 on 2022-03-15 21:23

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_category_name_alter_department_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rawitem',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('source'), django.db.models.expressions.F('name'), django.db.models.expressions.F('unit_size'), django.db.models.expressions.F('pack_quantity'), name='source-name-unit_size-pack_quantity'),
        ),
    ]
