# Generated by Django 4.0.1 on 2022-03-15 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rawitem_source-name-unit_size-pack_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawincomingitem',
            name='source_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.source'),
        ),
    ]
