# Generated by Django 4.0.1 on 2022-03-28 02:10

from django.db import migrations, models
import django.db.models.deletion
import inventory.models.raw_state


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_rawincomingitem_state_alter_usage_usage_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usage',
            options={'ordering': ('item_in_stock__raw_incoming_item__rawitem_obj__category__name', 'item_in_stock__raw_incoming_item__rawitem_obj__common_item_name_group__name__name')},
        ),
        migrations.AlterModelOptions(
            name='usagegroup',
            options={'ordering': ('-when', 'description')},
        ),
        migrations.AlterField(
            model_name='rawincomingitem',
            name='state',
            field=models.ForeignKey(default=inventory.models.raw_state.RawStateManager.initial_state, on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', related_query_name='raw_items', to='inventory.rawstate'),
        ),
    ]
