# Generated by Django 4.0.1 on 2022-03-16 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_rawincomingitem_rawitem_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawincomingitem',
            name='category_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='rawitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', related_query_name='raw_items', to='inventory.category'),
        ),
    ]
