# Generated by Django 4.0.1 on 2022-03-16 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_rawincomingitem_category_obj_alter_rawitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawincomingitem',
            name='department_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.department'),
        ),
    ]
