# Generated by Django 4.0.1 on 2022-03-16 22:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_rawincomingitem_department_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonitemname',
            name='raw_items',
        ),
        migrations.RemoveField(
            model_name='rawitem',
            name='common_item_name',
        ),
        migrations.CreateModel(
            name='CommonItemNameGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.commonitemname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='commonitemname',
            name='common_item_name_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='names', related_query_name='names', to='inventory.commonitemnamegroup'),
        ),
        migrations.AddField(
            model_name='rawitem',
            name='common_item_name_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.commonitemnamegroup'),
        ),
    ]
