# Generated by Django 4.0.1 on 2022-03-29 22:40

from django.db import migrations, models
import django.db.models.deletion
import inventory.models.raw_state
import scrap.models.fields.decimal_field
import scrap.models.fields.money_field


def get_prices(self):
    if not self.delivered_quantity or not self.pack_quantity:
        return {
            "price_per_pack": 0.0,
            "price_per_unit": 0.0,
            "price_per_count": 0.0,
        }
    price_per_unit = self.extended_price / self.delivered_quantity / self.pack_quantity
    price_per_count = price_per_unit / self.unit_quantity
    pack_price = price_per_unit * self.pack_quantity  # NOTE: tax got included by using extended_price
    return {
        "price_per_pack": round(pack_price, 4),
        "price_per_unit": round(price_per_unit, 4),
        "price_per_count": round(price_per_count, 4),
    }


def forwards_func(apps, schema_editor):
    ItemInStock = apps.get_model("inventory", "ItemInStock")
    db_alias = schema_editor.connection.alias
    items_to_update = []
    for item in ItemInStock.objects.using(db_alias).all():
        item.count_price = get_prices(item.raw_incoming_item)['price_per_count']
        items_to_update.append(item)
        if len(items_to_update) >= 200:
            ItemInStock.objects.using(db_alias).bulk_update(items_to_update, fields=('count_price', ))
            items_to_update.clear()
    if items_to_update:
        ItemInStock.objects.using(db_alias).bulk_update(items_to_update, fields=('count_price', ))
        items_to_update.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_iteminstock_unit_price_alter_rawincomingitem_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminstock',
            name='count_price',
            field=scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='iteminstock',
            name='remaining_count_quantity',
            field=scrap.models.fields.decimal_field.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rawincomingitem',
            name='state',
            field=models.ForeignKey(default=inventory.models.raw_state.RawStateManager.initial_state, on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', related_query_name='raw_items', to='inventory.rawstate'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop)
    ]
