# Generated by Django 4.0.1 on 2022-03-30 17:35

from django.db import migrations, models
import django.db.models.deletion
import inventory.models.raw_state
import scrap.models.fields.char_field
import scrap.models.fields.decimal_field


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_iteminstock_count_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='remaining_count_quantity_snapshot',
            field=scrap.models.fields.decimal_field.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usage',
            name='used_quantity_type',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='rawincomingitem',
            name='state',
            field=models.ForeignKey(default=inventory.models.raw_state.RawStateManager.initial_state, on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', related_query_name='raw_items', to='inventory.rawstate'),
        ),
    ]
