# Generated by Django 4.0.1 on 2022-03-16 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_commonitemname_raw_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonitemnamegroup',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category'),
        ),
    ]
