# Generated by Django 4.0.1 on 2022-04-11 18:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inventory.models.raw_state


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_usage_remaining_count_quantity_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonitemnamegroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commonitemnamegroup',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rawincomingitem',
            name='state',
            field=models.ForeignKey(default=inventory.models.raw_state.RawStateManager.initial_state, on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', related_query_name='raw_items', to='inventory.rawstate'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='item_in_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.iteminstock'),
        ),
    ]
