# Generated by Django 4.0.1 on 2022-03-17 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_commonitemnamegroup_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonitemnamegroup',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_groups', to='inventory.commonitemname'),
        ),
    ]
