# Generated by Django 4.0.1 on 2022-03-17 03:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_commonitemnamegroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonitemnamegroup',
            name='uncommon_item_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), blank=True, default=list, size=None),
        ),
    ]
