# Generated by Django 4.0.1 on 2022-04-26 02:52

from django.db import migrations, models
import django.db.models.deletion
import inventory.models.raw_state
import scrap.models.fields.char_field
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_f_item_price_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_name', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='name of the report', max_length=1024)),
                ('sort_value', models.IntegerField(default=1)),
                ('key', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='identifiable string for the value', max_length=1024)),
                ('value', scrap.models.fields.char_field.CharField(blank=True, default='', max_length=1024)),
            ],
            options={
                'ordering': ['report_name', 'sort_value', 'key', 'value'],
            },
        ),
        migrations.AlterField(
            model_name='rawincomingitem',
            name='state',
            field=models.ForeignKey(default=inventory.models.raw_state.RawStateManager.initial_state, on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', related_query_name='raw_items', to='inventory.rawstate'),
        ),
    ]
