# Generated by Django 4.0.1 on 2022-03-19 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_commonitemnamegroup_uncommon_item_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawitem',
            name='unit_quantity',
            field=models.IntegerField(default=1, help_text='For unit_size=ct/dz, this converts that to a number'),
        ),
        migrations.AddField(
            model_name='rawincomingitem',
            name='unit_quantity',
            field=models.IntegerField(default=1, help_text='For unit_size=ct/dz, this converts that to a number'),
        ),
        migrations.AlterField(
            model_name='rawincomingitem',
            name='rawitem_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='raw_incoming_items', to='inventory.rawitem'),
        ),
    ]
