---
# AttributeError: 'NoneType' object has no attribute 'startswith'
# Also: [WARNING]: Collection ansible.posix does not support Ansible version 2.12.4
# # This is for when multiple users need to ssh in.  Running ansible assumes there's at least one already there.
# - name: set authorized_key
#   ansible.posix.authorized_key:
#     user: pi
#     # key: "{{ lookup('file', '/home/devops/.ssh/id_rsa.pub') }}"
#     key: "{{ pi_authorized_key }}"
#     state: present
#   when: pi_authorized_key != ""

- name: set private key file
  copy:
    content: "{{ pi_priv_key }}"
    dest: "{{ default_home_dir }}/.ssh/id_rsa"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: "0600"

- name: set public key file
  copy:
    content: "{{ pi_pub_key }}"
    dest: "{{ default_home_dir }}/.ssh/id_rsa.pub"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: "0644"

# eval "$(ssh-agent -s)"
#
# - name: Added
#     shell: |
#       eval "$(ssh-agent)"
#       ssh-add ~/.ssh/id_rsa_svn_ssh