# Generated by Django 4.0.6 on 2023-08-10 03:26

import django.contrib.postgres.fields
from django.db import migrations, models
import scrap.models.fields.char_field
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', scrap.models.fields.char_field.CharField(blank=True, default='', max_length=1024)),
                ('source', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='url if from a site.  Book/page, etc?', max_length=1024)),
                ('description', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='General description', max_length=1024)),
                ('reason_to_not_make', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='Argument to not make this.  More definitive for filtering', max_length=1024)),
                ('star_acceptance', models.IntegerField(help_text='How well did people like it?', null=True)),
                ('star_effort', models.IntegerField(help_text='How much fun was it to make?', null=True)),
                ('common_multipliers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
