# Generated by Django 4.0.6 on 2023-08-14 00:17

from django.db import migrations, models
import django.db.models.deletion
import scrap.models.fields.char_field
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipecomment_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('step_number', models.IntegerField(default=1)),
                ('optional', models.BooleanField(default=False, help_text='Can this step be skipped?')),
                ('text', scrap.models.fields.char_field.CharField(blank=True, default='', max_length=2048)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', related_query_name='steps', to='recipe.recipe')),
            ],
            options={
                'ordering': ['recipe', 'step_number'],
            },
        ),
    ]
