# Generated by Django 4.0.6 on 2023-08-14 17:19

from django.db import migrations, models
import scrap.models.fields.char_field
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipestep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', scrap.models.fields.char_field.CharField(blank=True, default='', max_length=1024)),
                ('likely_source', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='Best guess where this would be purchased', max_length=1024)),
                ('description', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='General description', max_length=1024)),
                ('likely_container', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='To help with finding infrequently used items', max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
