# Generated by Django 4.0.6 on 2023-08-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name', 'likely_source']},
        ),
    ]
