# Generated by Django 4.0.6 on 2023-08-14 18:52

from django.db import migrations
import scrap.models.fields.char_field
import scrap.models.fields.decimal_field


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='metric_quantity',
            field=scrap.models.fields.decimal_field.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='metric_unit',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='us_quantity',
            field=scrap.models.fields.decimal_field.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='us_unit',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', max_length=1024),
        ),
    ]
