# Generated by Django 4.0.6 on 2023-08-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_recipeingredient_metric_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecomment',
            options={'ordering': ['recipe', '-pinned', '-created']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='template',
            field=models.BooleanField(default=False, help_text='Use this as a template - do not include on normal lists'),
        ),
    ]
