# Generated by Django 4.0.6 on 2023-08-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_searchcriteria'),
        ('recipe', '0009_alter_recipecomment_options_recipe_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='saved_search',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_items', related_query_name='recipe_items', to='inventory.searchcriteria'),
        ),
    ]
