# Generated by Django 4.0.1 on 2022-01-31 03:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_object_id', models.UUIDField(blank=True, null=True)),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='CommonItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='primary name')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('current_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('common_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.commonitem')),
            ],
        ),
        migrations.CreateModel(
            name='ItemChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_item_object_id', models.UUIDField(blank=True, null=True)),
                ('previous_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('change_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('new_quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.change')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('source_item_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='CommonItemNames',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, verbose_name='alternate name')),
                ('common_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_names', to='inventory.commonitem')),
            ],
        ),
    ]
