# Generated by Django 4.1 on 2022-08-15 19:08

from django.db import migrations
import scrap.models.fields.char_field


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceitem',
            name='scanned_filename',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', help_text='name of the scanned image file in case we need to verify data', max_length=1024),
        ),
    ]
