# Generated by Django 4.0.1 on 2022-01-31 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchange',
            name='applied',
            field=models.BooleanField(default=False, verbose_name='The change been applied'),
        ),
        migrations.AlterField(
            model_name='itemchange',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
    ]
