# Generated by Django 4.0.1 on 2022-01-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemchange',
            name='new_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemchange',
            name='previous_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
