# Generated by Django 4.0.1 on 2022-01-31 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_itemchange_applied_alter_itemchange_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_size',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='item',
            name='common_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.commonitem'),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='original_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
