# Generated by Django 4.0.1 on 2022-02-01 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_itemchange_new_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommonItemNames',
            new_name='CommonItemOtherName',
        ),
    ]
