# Generated by Django 4.1 on 2022-08-15 21:56

import django.contrib.postgres.fields
from django.db import migrations, models
import scrap.models.fields.char_field
import scrap.models.fields.money_field


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sourceitem_scanned_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceitem',
            name='customer_number',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='discrepancy',
            field=scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, help_text='to hold the difference between extended_cost and calculating from quantity/pack_cost', max_digits=10),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='extended_cost',
            field=scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, help_text='includes tax and any shipping fees', max_digits=10),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='line_item_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='order_number',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='pack_cost',
            field=scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='po_text',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='sourceitem',
            name='individual_weights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=4, max_digits=8), default=list, size=None),
        ),
    ]
