# Generated by Django 4.0.1 on 2022-02-01 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0003_rename_commonitemnames_commonitemothername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='source',
        ),
        migrations.RemoveField(
            model_name='itemchange',
            name='source_item',
        ),
        migrations.AddField(
            model_name='change',
            name='source_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'incoming'), ('model', 'IncomingItemGroup')), models.Q(('app_label', 'inventory'), ('model', 'Adjustment')), models.Q(('app_label', 'inventory'), ('model', 'Usage')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='change',
            name='source_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemchange',
            name='source_item_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'incoming'), ('model', 'IncomingItem')), models.Q(('app_label', 'inventory'), ('model', 'AdjustmentItem')), models.Q(('app_label', 'inventory'), ('model', 'UsageItem')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='itemchange',
            name='source_item_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
