# Generated by Django 4.1 on 2022-08-15 22:08

from django.db import migrations
import scrap.models.fields.char_field


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_sourceitem_customer_number_sourceitem_discrepancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceitem',
            name='source_category',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', help_text="Source-specific category.  Need our own as some of these don't make sense.", max_length=1024),
        ),
    ]
