# Generated by Django 4.0.1 on 2022-02-01 03:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_change_source_remove_itemchange_source_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UsageItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_items', to='inventory.item')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.usage')),
            ],
        ),
        migrations.CreateModel(
            name='AdjustmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_items', to='inventory.item')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.adjustment')),
            ],
        ),
    ]
