# Generated by Django 4.1 on 2022-08-16 01:39

import django.contrib.postgres.fields
from django.db import migrations, models
import scrap.models.fields.char_field
import scrap.models.wide_filter
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_sourceitem_source_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cryptic_name', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='Source-specific name of item as it appears on invoices', max_length=1024)),
                ('verbose_name', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='More human-readable name of the item', max_length=1024)),
                ('common_names', django.contrib.postgres.fields.ArrayField(base_field=scrap.models.fields.char_field.CharField(blank=True, default='', max_length=1024), default=list, size=None)),
            ],
            options={
                'abstract': False,
            },
            bases=(scrap.models.wide_filter.WideFilterModelMixin, models.Model),
        ),
    ]
