# Generated by Django 4.1 on 2022-08-16 03:33

from django.db import migrations
import scrap.models.fields.char_field


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_commonname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceitem',
            name='pack_quantity',
            field=scrap.models.fields.char_field.CharField(blank=True, default='1', help_text='For a pack of 6 #10 cans, this would be 6.', max_length=1024),
        ),
    ]
