# Generated by Django 4.0.1 on 2022-02-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_adjustment_usage_usageitem_adjustmentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='type',
            field=models.CharField(default='', max_length=1024, verbose_name='Adjustment type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usage',
            name='who',
            field=models.CharField(default='', max_length=1024, verbose_name='Who used this stuff'),
            preserve_default=False,
        ),
    ]
