# Generated by Django 4.0.1 on 2022-02-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0006_adjustment_type_usage_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='adjustmentitem',
            name='unit_size',
            field=models.CharField(default='count', max_length=1024),
        ),
        migrations.AddField(
            model_name='usageitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usageitem',
            name='unit_size',
            field=models.CharField(default='count', max_length=1024),
        ),
        migrations.AlterField(
            model_name='change',
            name='source_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'incoming'), ('model', 'incomingitemgroup')), models.Q(('app_label', 'inventory'), ('model', 'adjustment')), models.Q(('app_label', 'inventory'), ('model', 'usage')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
