# Generated by Django 4.0.6 on 2022-08-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_sourceitem_pack_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceitem',
            name='use_type',
            field=models.CharField(choices=[('BP', 'By Pack'), ('BU', 'By Unit'), ('BC', 'By Count')], default='BU', max_length=2),
        ),
    ]
