# Generated by Django 4.0.1 on 2022-02-01 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0007_adjustmentitem_quantity_adjustmentitem_unit_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemchange',
            name='source_item_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'incoming'), ('model', 'incomingitem')), models.Q(('app_label', 'inventory'), ('model', 'adjustmentitem')), models.Q(('app_label', 'inventory'), ('model', 'usageitem')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
