# Generated by Django 4.0.6 on 2022-08-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_sourceitem_use_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceitem',
            name='remaining_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
