# Generated by Django 4.0.6 on 2022-08-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_sourceitem_remaining_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceitem',
            name='remaining_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
