# Generated by Django 4.0.1 on 2022-02-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_adjustment_action_date_adjustment_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='who',
            field=models.CharField(default='nobody', max_length=1024, verbose_name='Who made the adjustment'),
            preserve_default=False,
        ),
    ]
