# Generated by Django 4.0.6 on 2022-08-22 19:14

from django.db import migrations, models
import django.db.models.deletion
import scrap.models.fields.char_field
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_sourceitem_remaining_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseTypeOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cryptic_name', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='Source-specific name of item as it appears on invoices', max_length=1024, null=True)),
                ('verbose_name', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='More human-readable name of the item', max_length=1024, null=True)),
                ('item_code', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='String of text that should uniquely identify the item', max_length=1024, null=True)),
                ('extra_code', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='A second code or whatever.', max_length=1024, null=True)),
                ('use_type', models.CharField(choices=[('BP', 'By Pack'), ('BU', 'By Unit'), ('BC', 'By Count')], default='BP', max_length=2)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.source')),
            ],
        ),
    ]
