# Generated by Django 4.0.1 on 2022-02-02 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_adjustment_who'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ['-action_date', '-created']},
        ),
    ]
