# Generated by Django 4.0.6 on 2022-09-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_usetypeoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceitem',
            name='remaining_count_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='remaining_pack_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='remaining_unit_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
