# Generated by Django 4.0.6 on 2022-10-03 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_sourceitem_remaining_count_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourceitem',
            options={'ordering': ['-delivered_date', 'source_id', 'order_number', 'line_item_number']},
        ),
    ]
