# Generated by Django 4.0.6 on 2022-10-03 02:39

from django.db import migrations, models


forward_sql = """
UPDATE inventory_sourceitem
SET
    remaining_count_quantity = CASE WHEN remaining_count_quantity IS NULL THEN 0 ELSE remaining_count_quantity END,
    remaining_pack_quantity = CASE WHEN remaining_pack_quantity IS NULL THEN 0 ELSE remaining_pack_quantity END,
    remaining_quantity = CASE WHEN remaining_quantity IS NULL THEN 0 ELSE remaining_quantity END,
    remaining_unit_quantity = CASE WHEN remaining_unit_quantity IS NULL THEN 0 ELSE remaining_unit_quantity END
WHERE (remaining_count_quantity IS NULL)
    OR (remaining_pack_quantity IS NULL)
    OR (remaining_quantity IS NULL)
    OR (remaining_unit_quantity IS NULL);
"""


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_sourceitem_options'),
    ]

    operations = [
        migrations.RunSQL(forward_sql, reverse_sql=migrations.RunSQL.noop),
        migrations.AlterField(
            model_name='sourceitem',
            name='remaining_count_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sourceitem',
            name='remaining_pack_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sourceitem',
            name='remaining_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sourceitem',
            name='remaining_unit_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
