# Generated by Django 4.0.1 on 2022-02-05 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_category_options_alter_commonitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='itemchange',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commonitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_items', to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='commonitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='common_items', to='inventory.location'),
        ),
    ]
