# Generated by Django 4.0.2 on 2022-02-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_item_unit_cost_itemchange_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchange',
            name='extended_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
