# Generated by Django 4.0.6 on 2022-10-30 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_sourceitem_remaining_count_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
