# Generated by Django 4.0.6 on 2022-11-03 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_sourceitem_created_sourceitem_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['name']},
        ),
    ]
