# Generated by Django 4.0.2 on 2022-02-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_itemchange_extended_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchange',
            name='line_item_position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
    ]
