# Generated by Django 4.0.2 on 2022-02-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_itemchange_line_item_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentitem',
            name='line_item_position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='usageitem',
            name='line_item_position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
    ]
