# Generated by Django 4.0.6 on 2023-05-28 14:48
import pathlib

from django.db import migrations

forward_sql = (pathlib.Path(__file__).parent.parent / 'sql/vw_orders_entered_today-0001.sql').read_text()

reverse_sql = """
DROP VIEW vw_orders_entered_today;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_source_options'),
    ]

    operations = [
        migrations.RunSQL(forward_sql, reverse_sql=reverse_sql),
    ]
