# Generated by Django 4.0.2 on 2022-02-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_adjustmentitem_line_item_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemchange',
            name='applied',
        ),
        migrations.AddField(
            model_name='change',
            name='applied_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='The change been applied'),
        ),
        migrations.AddField(
            model_name='itemchange',
            name='applied_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='The change been applied'),
        ),
    ]
