# Generated by Django 4.0.6 on 2023-05-28 14:48
import pathlib

from django.db import migrations

drop_view_sql = """
-- This changes the columns of the output so cannot simply 'CREATE OR REPLACE'.
DROP VIEW vw_orders_entered_today;
"""

forward_sql_from_file = (pathlib.Path(__file__).parent.parent / 'sql/vw_orders_entered_today-0002.sql').read_text()

reverse_sql_from_file = (pathlib.Path(__file__).parent.parent / 'sql/vw_orders_entered_today-0001.sql').read_text()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_vw_orders_entered_today_0001'),
    ]

    operations = [
        migrations.RunSQL(drop_view_sql, reverse_sql=reverse_sql_from_file),
        migrations.RunSQL(forward_sql_from_file, reverse_sql=drop_view_sql),
    ]
