# Generated by Django 4.0.6 on 2023-08-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_searchcriteria_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchcriteria',
            options={'ordering': ['category', 'name']},
        ),
    ]
