# Generated by Django 4.0.1 on 2022-02-10 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_configitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.configitem'),
        ),
    ]
