# Generated by Django 4.0.6 on 2023-09-11 16:23

from django.db import migrations
import scrap.models.fields.char_field


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_searchcriteria_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchcriteria',
            name='url_slug',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', help_text='string to use on a url.  Generated by slugify.', max_length=1024),
        ),
    ]
