# Generated by Django 4.0.1 on 2022-02-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_configitem_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usageitem',
            options={'ordering': ('parent', 'line_item_position')},
        ),
    ]
