# Generated by Django 4.0.1 on 2022-02-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_usageitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonitem',
            options={'ordering': ('name', 'created')},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('common_item__name', 'created')},
        ),
    ]
