# Generated by Django 4.0.1 on 2022-02-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_commonitem_options_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonitem',
            name='comment',
            field=models.CharField(blank=True, default='', help_text='anything particularly interesting about this item (in general, not specific to any brand)', max_length=1024),
        ),
    ]
