# Generated by Django 4.2.16 on 2024-10-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_common_name_prices_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchcriteria',
            name='version',
            field=models.CharField(default='0'),
        ),
    ]
