# Generated by Django 4.2.16 on 2024-10-21 00:15

from django.db import migrations, models
import scrap.models.fields.char_field
import scrap.models.fields.decimal_field
import scrap.models.fields.money_field


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_source_totals_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceitem',
            name='adjusted_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='adjusted_pack_cost',
            field=scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='adjusted_pack_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='adjusted_per_weight_cost',
            field=scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='adjusted_weight',
            field=scrap.models.fields.decimal_field.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sourceitem',
            name='adjusted_weight_unit',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='version',
            field=scrap.models.fields.char_field.CharField(blank=True, default='0', max_length=1024),
        ),
    ]
