# Generated by Django 4.2.16 on 2024-10-24 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_populate_adjusted_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourceitem',
            name='remaining_unit_quantity',
        ),
    ]
