# Generated by Django 4.2.16 on 2024-10-27 22:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
import scrap.models.fields.char_field
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_remove_sourceitem_remaining_unit_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('notes', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='Anything special about this usage group as a whole.', max_length=1024)),
                ('start_date', models.DateField(help_text='The start date of the usage group.')),
                ('end_date', models.DateField(help_text='The end date of the usage group.')),
                ('open', models.BooleanField(default=True, help_text='Whether the usage group is actively being added to.')),
                ('adjustment_type', models.CharField(choices=[('discard', 'Discard'), ('order', 'Order'), ('recount', 'Recount'), ('sale', 'Sale'), ('unknown', 'Unknown'), ('usage', 'Usage')], default='unknown', max_length=20)),
            ],
            options={
                'ordering': ['created', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('notes', scrap.models.fields.char_field.CharField(blank=True, default='', help_text='Anything special about this adjustment.', max_length=1024)),
                ('pack_quantity', models.IntegerField(default=0)),
                ('count_quantity', models.IntegerField(default=0)),
                ('no_change', models.BooleanField(default=True)),
                ('adjustment_date', models.DateField(default=datetime.date.today, help_text='When the adjustment actually took place')),
                ('adjustment_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', related_query_name='adjustments', to='inventory.adjustmentgroup')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', related_query_name='adjustments', to='inventory.sourceitem')),
            ],
            options={
                'ordering': ['adjustment_date', 'created'],
            },
        ),
    ]
