# Generated by Django 4.2.18 on 2025-01-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_adjustmentgroup_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceitem',
            name='use_type',
            field=models.CharField(choices=[('BP', 'By Pack'), ('BU', 'By Unit'), ('BC', 'By Count')], default='BP', max_length=2),
        ),
    ]
