# Generated by Django 4.0.6 on 2022-09-15 01:27

from django.db import migrations, models
import django.db.models.deletion
import scrap.models.fields.char_field
import scrap.models.fields.money_field
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', scrap.models.fields.char_field.CharField(blank=True, default='', max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, help_text='1pk, 3pk, 6pk, 8pk, dz')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OnSaleItemPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_made', models.DateField()),
                ('packs_made', models.IntegerField(default=0, help_text='how many packs put up for sale')),
                ('date_frozen', models.DateField(blank=True, null=True)),
                ('packs_frozen', models.IntegerField(blank=True, default=0, help_text='how many packs were put into freezer', null=True)),
                ('sale_price_fresh', scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, max_digits=10)),
                ('sale_price_frozen', scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, help_text='Usually a dollar off from fresh price', max_digits=10)),
                ('material_cost', scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, help_text='cost of materials for the pack.', max_digits=10)),
                ('item_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.itempack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('sold', 'Sold'), ('trash', 'Trashed'), ('giveaway', 'Gave away'), ('pantry', 'Pantry'), ('bingo', 'Bingo'), ('discount', 'Discount'), ('coupon', 'Coupon')], default='sold', max_length=25)),
                ('sale_price', scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, help_text='Should mostly be the asking price but could be discounted.', max_digits=10)),
                ('packs_sold', models.IntegerField(default=1)),
                ('date_sold', models.DateField()),
                ('is_eod', models.BooleanField(default=False, help_text='Is this an adjustment for the end of a given day?')),
                ('on_sale_item_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.onsaleitempack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('date_made', models.DateField()),
                ('pickup_date', models.DateField()),
                ('who', scrap.models.fields.char_field.CharField(blank=True, default='', max_length=1024)),
                ('sale_price_per_pack', scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, max_digits=10)),
                ('sale_price', scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, max_digits=10)),
                ('material_cost_per_pack', scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, help_text='cost of materials for a single pack.', max_digits=10)),
                ('material_cost', scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, help_text='cost of materials for the order.', max_digits=10)),
                ('item_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.itempack')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
