# Generated by Django 4.0.6 on 2022-09-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('bread', 'Bread'), ('cake', 'Cake'), ('cookie', 'Cookie'), ('other', 'Other')], default='cookie', max_length=25),
        ),
    ]
