# Generated by Django 4.0.6 on 2022-09-16 02:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_order_date_ordered_alter_order_date_made_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
