# Generated by Django 4.0.6 on 2022-09-18 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempack',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_packs', related_query_name='item_packs', to='market.item'),
        ),
    ]
