# Generated by Django 4.0.6 on 2022-09-18 19:18

from django.db import migrations, models
import django.db.models.deletion
import scrap.models.fields.char_field
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_itempack_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', scrap.models.fields.char_field.CharField(blank=True, default='', max_length=1024)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', related_query_name='tags', to='market.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
