# Generated by Django 4.0.6 on 2022-09-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempack',
            options={'ordering': ['item', 'quantity']},
        ),
    ]
