# Generated by Django 4.0.6 on 2022-09-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_itempack_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_name='items', related_query_name='items', to='market.tag'),
        ),
    ]
