# Generated by Django 4.0.6 on 2022-09-18 19:48

from django.db import migrations, models
import django.db.models.deletion
import scrap.models.fields.money_field
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_remove_tag_item_item_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item_pack',
        ),
        migrations.RemoveField(
            model_name='order',
            name='material_cost_per_pack',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sale_price_per_pack',
        ),
        migrations.AlterField(
            model_name='order',
            name='material_cost',
            field=scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, help_text='cost of materials for all items in the order.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='sale_price',
            field=scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, help_text='sale price for all items in the order', max_digits=10),
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_item_position', models.IntegerField(default=0)),
                ('quantity', models.IntegerField()),
                ('sale_price_per_pack', scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, max_digits=10)),
                ('sale_price', scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, max_digits=10)),
                ('material_cost_per_pack', scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, help_text='cost of materials for a single pack.', max_digits=10)),
                ('material_cost', scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, help_text='cost of materials for the order.', max_digits=10)),
                ('item_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.itempack')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', related_query_name='line_items', to='market.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
