# Generated by Django 4.0.6 on 2022-09-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_item_material_cost_per_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='items', related_query_name='items', to='market.tag'),
        ),
    ]
