# Generated by Django 4.0.6 on 2022-09-19 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_alter_item_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['category', 'name']},
        ),
    ]
