# Generated by Django 4.0.6 on 2022-09-19 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='item_pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.itempack'),
        ),
    ]
