# Generated by Django 4.0.6 on 2022-09-19 17:59

from django.db import migrations
import scrap.models.fields.char_field


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_alter_orderlineitem_item_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='item_pack_str',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', help_text='Backup of str(item_pack) in case the item_pack is deleted.', max_length=1024, null=True),
        ),
    ]
