# Generated by Django 4.0.6 on 2022-09-19 20:44

from django.db import migrations
import scrap.models.fields.money_field


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_orderlineitem_item_pack_str'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderlineitem',
            options={'ordering': ['order', 'line_item_position']},
        ),
        migrations.AddField(
            model_name='itempack',
            name='suggested_sale_price_per_pack',
            field=scrap.models.fields.money_field.MoneyField(blank=True, decimal_places=4, default=0, max_digits=10, null=True),
        ),
    ]
