# Generated by Django 4.0.6 on 2023-06-04 03:12

from django.db import migrations, models
import django.db.models.deletion
import scrap.models.fields.char_field
import scrap.models.fields.money_field
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_alter_orderlineitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnSaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=12)),
                ('date_made', models.DateField()),
                ('packs_made', models.IntegerField(default=0, help_text='how many packs put up for sale')),
                ('date_frozen', models.DateField(blank=True, null=True)),
                ('packs_frozen', models.IntegerField(blank=True, default=0, help_text='how many packs were put into freezer', null=True)),
                ('sale_price_fresh', scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, max_digits=10)),
                ('sale_price_frozen', scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, help_text='Usually a dollar off from fresh price', max_digits=10)),
                ('material_cost', scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, help_text='cost of materials for the pack.', max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='onsaleitempack',
            name='item_pack',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='item_pack',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='item_pack_str',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='on_sale_item_pack',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.item'),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='item_str',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', help_text='Backup of str(item) in case the item is deleted.', max_length=1024, null=True),
        ),
        migrations.DeleteModel(
            name='ItemPack',
        ),
        migrations.DeleteModel(
            name='OnSaleItemPack',
        ),
        migrations.AddField(
            model_name='sale',
            name='on_sale_item',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, to='market.onsaleitem'),
            preserve_default=False,
        ),
    ]
