# Generated by Django 4.0.6 on 2023-06-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_onsaleitem_remove_onsaleitempack_item_pack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='pack_quantity',
            field=models.IntegerField(default=12, help_text='count per bag/plate.'),
            preserve_default=False,
        ),
    ]
