# Generated by Django 4.0.6 on 2023-06-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_orderlineitem_pack_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='pack_quantity',
            field=models.IntegerField(default=12, help_text='count per bag/plate.'),
        ),
    ]
