# Generated by Django 4.0.6 on 2023-06-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_alter_orderlineitem_pack_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
