# Generated by Django 4.0.6 on 2023-06-04 19:10

from django.db import migrations, models
import market.models.order


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_order_date_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_ordered',
            field=models.TimeField(default=market.models.order.now),
        ),
    ]
