# Generated by Django 4.0.6 on 2023-06-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_order_time_ordered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_ordered', '-time_ordered', 'who', 'id']},
        ),
    ]
