# Generated by Django 4.0.6 on 2023-06-06 17:06

from django.db import migrations, models
import scrap.models.fields.char_field


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='how_paid',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', help_text='card/cash/gift certificate.  Is this even needed?', max_length=1024),
        ),
        migrations.AddField(
            model_name='order',
            name='reason_for_order',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', help_text='Because people keep asking me.', max_length=1024),
        ),
        migrations.AddField(
            model_name='order',
            name='who_is_picking_up',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', help_text="If different than 'who'", max_length=1024),
        ),
    ]
