# Generated by Django 4.0.6 on 2023-06-06 17:11

from django.db import migrations
import scrap.models.fields.char_field


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0027_order_expected_date_order_expected_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_number',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', help_text='In case there is an issue and/or pickup is delayed', max_length=1024),
        ),
    ]
