# Generated by Django 4.2.16 on 2025-05-19 17:29

from django.db import migrations
import scrap.models.fields.char_field
import scrap.models.fields.money_field


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0029_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, help_text='discount applied to the order.', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_text',
            field=scrap.models.fields.char_field.CharField(blank=True, default='', help_text='Brief explanation of the discount.', max_length=1024),
        ),
        migrations.AddField(
            model_name='order',
            name='discounted_price',
            field=scrap.models.fields.money_field.MoneyField(decimal_places=4, default=0, help_text='sale price minus discount.', max_digits=10),
        ),
    ]
